---
title: "AY 2025-2026 Semester 1 Seminar Schedule"
execute:
  echo: false
  warning: false
  message: false
toc-expand: true
---

```{r}
source("R/helpers.R")

#| echo: false
#| message: false
```


```{r}
#| echo: false
#| message: false

# library(knitr)
# library(kableExtra)
# Example data
seminars_pre <- read_csv("./data/AY25-26_sem_1_timetable.csv")

```

# Timetable

```{r}
seminar_table <- create_timetable(seminars_pre)
seminar_table
```

<!-- If you would like add the seminar series to you calendar, you can click the button below, select outlook and name the subscribed calendar something like "MACSI Seminar Series". Any changes changes to the seminar schedule should be reflected in this calendar.  -->


<!-- <a class="btn btn-primary" href="webcal:https://macsi-seminars.github.io/calendar/macsi-seminar-series.ics"> -->
<!--   Subscribe (webcal) -->
<!-- </a> -->

<!-- <a href="/fixtures-results/downloadable-fixtures/" target="_blank" title="Download the Fixture List Here"> <span class="fix-cal-text"> Add to Calendar</span><span class="fix-cal-icon"><i class="fa fa-calendar-plus-o" aria-hidden="true"></i></span></a> -->

# Abstracts

As seminar abstracts become available from the speakers this page will be updated. 

---

```{r}
#| results: asis

create_abstracts_text(seminars_pre)

```

